# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"6\n\x0eProductoPedido\x12\x12\n\nproductoId\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\"K\n\x12\x43reateOrderRequest\x12\x11\n\tusuarioId\x18\x01 \x01(\t\x12\"\n\tproductos\x18\x02 \x03(\x0b\x32\x0f.ProductoPedido\"\x80\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tusuarioId\x18\x02 \x01(\t\x12\"\n\tproductos\x18\x03 \x03(\x0b\x32\x0f.ProductoPedido\x12\x0e\n\x06\x65stado\x18\x04 \x01(\t\x12\x15\n\rfechaCreacion\x18\x05 \x01(\t\x12\r\n\x05total\x18\x06 \x01(\x01\x32:\n\x0cOrderService\x12*\n\x0b\x43reateOrder\x12\x13.CreateOrderRequest\x1a\x06.OrderB\x1b\xaa\x02\x18OrderNotification.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\030OrderNotification.Protos'
  _globals['_PRODUCTOPEDIDO']._serialized_start=15
  _globals['_PRODUCTOPEDIDO']._serialized_end=69
  _globals['_CREATEORDERREQUEST']._serialized_start=71
  _globals['_CREATEORDERREQUEST']._serialized_end=146
  _globals['_ORDER']._serialized_start=149
  _globals['_ORDER']._serialized_end=277
  _globals['_ORDERSERVICE']._serialized_start=279
  _globals['_ORDERSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
